- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: pip
        state: latest
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
