---
- name : install ldap
  hosts: all
  become: true
  tasks:
    - name: CLONE REPO
      ansible.builtin.git:
        repo: 'https://github.com/lakedjass/tools.git'
        dest: /opt/tools/
    - name: docker compose up
      community.docker.docker_compose:
        project_src: /opt/tools/docker/openldap
        state: present
        restarted: true
    - name: Install  dependencies
      ansible.builtin.apt:
        name:
          - python3-ldap
        state: present
    - name: "create cn=users,dc=cyberzone-sec,dc=com entry"
      community.general.ldap_entry:
        dn: "cn=users,dc=cyberzone-sec,dc=com"
        objectClass:
          - posixGroup
          - top
        attributes:
          cn: "users"
          gidnumber: 1
        server_uri: ldap://localhost/
        bind_dn: cn=admin,dc=cyberzone-sec,dc=com
        bind_pw: "{{ LDAP_ADMIN_PASSWORD }}"
