---
- name : install ldap
  hosts: all
  become: true
  tasks:
    - name: Install  dependencies
      ansible.builtin.apt:
        name:
          - python3-ldap
        state: present
    - name: "create cn={{ LDAP_CN }},cn=users,dc=cyberzone-sec,dc=com entry"
      community.general.ldap_entry:
        dn: "cn={{ LDAP_CN }},cn=users,dc=cyberzone-sec,dc=com"
        objectClass:
          - inetOrgPerson
          - posixAccount
          - top
        attributes:
          cn: "{{ LDAP_CN }}"
          sn: "{{ LDAP_SN }}"
          uid: "{{ LDAP_CN }}"
          userPassword: "{{ LDAP_PASSWORD }}"
          uidNumber: "{{ LDAP_UIDNUMBER }}"
          gidNumber: 1
          loginShell: /bin/bash
          homeDirectory: "/home/users/{{ LDAP_CN }}"
          givenName: "{{ LDAP_GIVENNAME }}"
          mail: "{{ LDAP_EMAIL }}"
          telephonenumber: "{{ LDAP_PHONE }}"
        server_uri: ldap://localhost/
        bind_dn: cn=admin,dc=cyberzone-sec,dc=com
        bind_pw: "{{ LDAP_ADMIN_PASSWORD }}"
