---
- name : install ldap
  hosts: all
  become: true
  tasks:
    - name: Install  dependencies
      ansible.builtin.apt:
        name:
          - python3-ldap
        state: present
    - name: "create cn={{ USER_USERNAME }},cn=users,dc=cyberzone-sec,dc=com entry"
      community.general.ldap_entry:
        dn: "cn={{ USER_USERNAME }},cn=users,dc=cyberzone-sec,dc=com"
        objectClass:
          - inetOrgPerson
          - posixAccount
          - top
        attributes:
          cn: "{{ USER_USERNAME }}"
          sn: "{{ USER_USERNAME }}"
          uid: "{{ USER_USERNAME }}"
          userPassword: "{{ USER_PASSWORD }}"
          uidNumber: "{{ USER_UID }}"
          gidNumber: 1
          loginShell: /bin/bash
          homeDirectory: "/home/users/{{ USER_USERNAME }}"
          givenName: "{{ USER_USERNAME }}"
          mail: "{{ USER_USERNAME }}@cyberzone-sec.com"
        server_uri: ldap://localhost/
        bind_dn: cn=admin,dc=cyberzone-sec,dc=com
        bind_pw: "{{ LDAP_ADMIN_PASSWORD }}"
